apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-project
  template:
    metadata:
      labels:
        app: cicd-project
    spec:
      containers:
      - name: cicd-project
        image: karishrat123/cicd-project:latest  # <-- your Docker Hub image
        ports:
        - containerPort: 5000
